services:
  mongodb:
    image: mongo
    env_file:
      - path: ./.env.local
        required: true
  

    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
