import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavButton } from "@/components/NavButton"
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-5 flex ">
          <NavButton children="Home" href="/" />
          <NavButton children="Dashboard" href="/dashboard" />
          <NavButton
            children={cookies().has("sessionToken") ? "Account" : "Login"}
            className="bg-blue-500 rounderd-lg"
            alignRight={true}
            href={cookies().has("sessionToken") ? "/account" : "/login"}
          />
        </nav>
        {children}
      </body>
    </html>
  );
}
